FROM node:20-alpine AS development

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:server1

FROM node:20-alpine AS production
ENV NODE_ENV=production
ENV PORT=4004
EXPOSE ${PORT}

WORKDIR /app

COPY --from=development /app/dist/apps/server1 ./

# Install production dependencies as root
RUN npm install --only=production

# Now switch to the non-root user
USER node

CMD ["node", "main"]
