FROM node:20-alpine AS development

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:server1

FROM node:20-alpine AS production


WORKDIR /app

COPY --from=development /app/dist/apps/server1 ./

# Install production dependencies as root
RUN npm install --only=production

# Now switch to the non-root user
USER node
ENV PORT=4004
CMD ["node", "main"]
