version: "3.9"
services:
  frontend:
    build:
      dockerfile: ./apps/frontend/Dockerfile
      target: development
      context: .
    command: npm run serve:frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
