FROM nginx:alpine

# Create SSL directory in the container
RUN mkdir -p /etc/nginx/ssl

# Copy SSL certificates from the NX root ssl-certs directory
COPY ./ssl-certs/nginx-selfsigned.crt /etc/nginx/ssl/nginx-selfsigned.crt
COPY ./ssl-certs/nginx-selfsigned.key /etc/nginx/ssl/nginx-selfsigned.key

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 443
